language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: "lrAo6i8xd+5A3iSxtKN4AIavqDIU8BCMVifG5Ml+anlJesqe4jYU/lbLHqGoG2erWw4QZV8eHIsL4cXU23h9CxR6H1dqubEv6D0wGSXm/OwcXCuEv4ulgiuv9Lgvj9ILlh/Sfq7ufLweIbP1vj3Q4IFMDHEiJV2R3Rk31CraJwl1WcmZ7qiKPyREZWItHJp8dDfDoKWWaSoYL26sT//jRYJDW0CVvksWcaF3aoXlbkxBJyzNMn14gd0ngBagkdmy2/+u0KEPQUBF76veNu+7wvgRg938FDeLjxwP2skokczagAR3xKrHrJRDQCqevoHL5cxKzsyJQsrFMRe+iPb4HC/+eImR1+raDnmwIFpdr1FMNdZKB00t6eqxwdyK2+G1+cpFX76xdde4grHbp7cl9hmbh3a/+6+8BctkfkZe8gM+hNgLYl0WA+Lsi7MGwBx/irWUr778f1U7I3ouXeOLAcBcsfFXdm5JqDKSvOqaAGkzylVrLWXtQ1i8ugkF7IMyqNLeBFdjdq3kTvycr51iO3XvHN4uRBQrxa1fcuXOsAXKizuSWkzpdXU+swt9I3QFX1lAHwa83NiY6EYBCa62/YXdtcsABKbD7F4X8Hm7/CD8pnlgLMKPpe7TNfhb167JBd4xxkYY3dbScR+JGe2H31dtrCTnZrHeaNU8Od9tvlY="
  file: ${TRAVIS_BUILD_DIR}/build/libs/ByteSwipe.jar'
  skip_cleanup: true
  on:
    repo: shadwelldacunha/ByteSwipe